# Generated by Django 4.2 on 2023-04-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_language_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
